#!/bin/bash

# Change to the wallpapers directory
cd ~/Pictures/wallpapers || exit
#remove spaces
for file in *\ *; do mv "$file" "${file// /_}"; done

# Get a random wallpaper file
wallpaper=$(ls | shuf -n 1)

#pick a random number between 0 and 1 to saturate the colorscheme
saturate=$(awk -v min=0.2 -v max=1.0 'BEGIN{srand(); print min+rand()*(max-min)}')

# Print the selected wallpaper
full_path=$(pwd)/$wallpaper
#if path is passed as argument skip the above
if [ -n "$1" ]; then
	full_path=$1
fi
rm -f ~/.config/hypr/hyprpaper.conf
echo "#this file is generated by randonwallsh each time you run it" >>~/.config/hypr/hyprpaper.conf
echo preload = $full_path >>~/.config/hypr/hyprpaper.conf
echo wallpaper = ,$full_path >>~/.config/hypr/hyprpaper.conf
echo splash = true >>~/.config/hypr/hyprpaper.conf
echo ipc = false >>~/.config/hypr/hyprpaper.conf
killall -q swww
swww img $full_path --transition-type random --transition-step 1 --transition-fps 90
wal --saturate $saturate -q -i $full_path -n -e
exit
