#!/bin/bash
mkdir $HOME/.cache/wal 2>/dev/null

# Default wallpaper directory
WALLPAPER_DIR="$HOME/Pictures/wallpapers"

# Check if -n flag is passed
if [ "$1" = "-n" ]; then
	WALLPAPER_DIR="$HOME/Pictures/wallpapers/nsfw"
	# Shift argument list to handle additional args properly
	shift
fi

cd "$WALLPAPER_DIR" || exit

# Create wallpapers cache file if it doesn't exist
touch ~/.cache/wal/wallpapers

# Delete the cache if it contains more than half of the wallpapers
wallpaper_count=$(ls | grep -E ".*\.(jpg|png|gif)" | wc -l)
cache_count=$(wc -l <~/.cache/wal/wallpapers)
if [ $cache_count -gt $(($wallpaper_count / 2)) ]; then
	rm -f ~/.cache/wal/wallpapers
	touch ~/.cache/wal/wallpapers
fi

# Get a random wallpaper file, only jpg, png and gif files
wallpaper=$(ls | grep -E ".*\.(jpg|png|gif)" | shuf -n 1)

# Check if the file is in the cache, if so we choose another
attempt=0
max_attempts=20 # Prevent infinite loop if all wallpapers are in cache
while grep -q "$wallpaper" ~/.cache/wal/wallpapers && [ $attempt -lt $max_attempts ]; do
	wallpaper=$(ls | grep -E ".*\.(jpg|png|gif)" | shuf -n 1)
	attempt=$((attempt + 1))
done

# Add the selected wallpaper to the cache
echo "$wallpaper" >>~/.cache/wal/wallpapers

# Print the selected wallpaper
full_path=$(pwd)/$wallpaper
#if path is passed as argument skip the above
if [ -n "$1" ]; then
	full_path=$1
fi
rm -f ~/.config/hypr/hyprpaper.conf
echo "#this file is generated by randonwallsh each time you run it" >>~/.config/hypr/hyprpaper.conf
echo preload = $full_path >>~/.config/hypr/hyprpaper.conf
echo wallpaper = ,$full_path >>~/.config/hypr/hyprpaper.conf
echo splash = true >>~/.config/hypr/hyprpaper.conf
echo ipc = false >>~/.config/hypr/hyprpaper.conf

# Random hellwal configuration
hellwal_opts="-m"

# Randomly choose mode (dark/light/color)
mode_options=("--dark" "--color")
selected_mode=${mode_options[$((RANDOM % 1))]}
hellwal_opts="$hellwal_opts $selected_mode"

# 50% chance to enable neon mode
if [ $((RANDOM % 100)) -lt 50 ]; then
	hellwal_opts="$hellwal_opts --neon-mode"
fi

# 10% chance to enable grayscale with random value
if [ $((RANDOM % 100)) -lt 10 ]; then
	hellwal_opts="$hellwal_opts --gray-scale 0.8"
fi

# Run hellwal with random options
hellwal -i $full_path $hellwal_opts

swww img $full_path --transition-type random
swaync-client -rs

# and keep only the last 5 commands
{
	# Create a temporary file
	temp_file=$(mktemp)

	# If lastrandomwall.txt exists, copy its content to the temp file
	if [ -f "$HOME/lastrandomwall.txt" ]; then
		cat "$HOME/lastrandomwall.txt" >"$temp_file"
	fi

	# Add the new command group
	{
		echo "########################################"
		echo "$(date "+%Y-%m-%d %H:%M:%S")"
		echo "hellwal -i $full_path $hellwal_opts"
		echo "swww img $full_path --transition-type random"
		echo "########################################"
		echo ""
	} >>"$temp_file"

	# Keep only the last 5 command groups (each group has 6 lines)
	tail -n 30 "$temp_file" >"$HOME/lastrandomwall.txt"

	# Remove the temporary file
	rm "$temp_file"
}
